export default
{
    "apiUrl": "http://localhost:8000",
    "endpoints": {
        "login": "/api/login",
        "getUserList": "/api/admin/users",
        "getUser": "/api/admin/user/%d",
        "getApiUser": "/api/get-user",
        "create": "/api/%s/create",
        "update": "/api/%s/update",
        "delete": "/api/%s/delete",
        "provider": "/api/provider/%d",
        "providerList": "/api/providers",
        "providerProperty": "/api/provider/%d/property/%d",
        "providerPropertyList": "/api/provider/%d/properties",
        "providerPropertyRelation": "/api/provider/property/relation/%d",
        "property": "/api/property/%d",
        "propertyList": "/api/properties",
        "category": "/api/category/%d",
        "categoryList": "/api/categories",
        "service": "/api/service/%d",
        "serviceList": "/api/services",
        "serviceResponseKeyList": "/api/service/response/key/list",
        "serviceResponseKey": "/api/service/response/key/%d",
        "serviceRequest": "/api/service/request/%d",
        "serviceRequestList": "/api/service/request/list",
        "serviceRequestParameterList": "/api/service/request/parameter/list",
        "serviceRequestParameter": "/api/service/request/parameter/%d",
        "serviceRequestConfigList": "/api/service/request/config/list",
        "serviceRequestConfig": "/api/service/request/config/%d",
    }
}